#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "rubygems_pq_tls_policy"

ok = Gem::PqTlsPolicy::Diagnostic.report($stdout)
exit(ok ? 0 : 1)
